language: go
go:
  - "1.11"

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: pages
  local-dir: public
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: dbibb.com
  on:
    branch: master