language: go
go:
  - "1.11"

branches:
  only:
    - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages