#baseURL = "http://localhost:9898/"
baseURL = "https://dbibb.com/"
languageCode = "en-us"
title = "Bad at Naming"
theme = "nofancy"

[params]
  highlight = "default"

  topmenu = "categories"

[author]
  name = "David Bibb"
  github = "kryptn"
  gaid = "UA-66798985-1"